/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFrames;

import Classes.Brand;
import Classes.Customer;
import Classes.Model;
import Classes.Product;
import Classes.Sales;
import Classes.Staff;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class SaleUpdateListFrame extends javax.swing.JFrame {

    /**
     * Creates new form SaleUpdateListFrame
     */
    public SaleUpdateListFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSales = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCustomer = new javax.swing.JTextField();
        txtStaff = new javax.swing.JTextField();
        txtDate = new javax.swing.JTextField();
        txtBrand = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 480));
        setModalExclusionType(null);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        tblSales.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Müşteri", "Satan Personel", "Ürün", "Satış Tarihi", "Fiyat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSalesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSales);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(240, 52, 590, 160);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel1.setText("Müşteri : ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 55, 64, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel2.setText("Satan Personel : ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 108, 116, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel3.setText("Ürün Marka :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 166, 89, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel4.setText("Satış Tarihi : ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 224, 88, 17);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel5.setText("Fiyat : ");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 287, 46, 17);

        txtCustomer.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        getContentPane().add(txtCustomer);
        txtCustomer.setBounds(144, 52, 87, 23);

        txtStaff.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        getContentPane().add(txtStaff);
        txtStaff.setBounds(144, 105, 87, 23);

        txtDate.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        getContentPane().add(txtDate);
        txtDate.setBounds(144, 221, 87, 23);

        txtBrand.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        getContentPane().add(txtBrand);
        txtBrand.setBounds(144, 163, 87, 23);

        txtPrice.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        getContentPane().add(txtPrice);
        txtPrice.setBounds(144, 284, 87, 23);

        btnBack.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        btnBack.setForeground(new java.awt.Color(0, 102, 102));
        btnBack.setText("<------");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(0, 0, 73, 25);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/foto/tech1.jpg"))); // NOI18N
        jLabel6.setMinimumSize(new java.awt.Dimension(850, 480));
        jLabel6.setPreferredSize(new java.awt.Dimension(702, 384));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, -10, 860, 490);

        setSize(new java.awt.Dimension(856, 499));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        
    List<Sales> listSales = Sales.Listing();  
    
    Object[][] data = new Object[listSales.size()][];    
    
     for (int i  = 0; i < data.length; i++) {
           
            data[i]= new Object[]
            {
                Customer.Searching(listSales.get(i).CustomerId).get(0).CustomerName +" "+ Customer.Searching(listSales.get(i).CustomerId).get(0).CustomerSurname,
                Staff.Searching(listSales.get(i).StaffId).get(0).StaffName +" "+ Staff.Searching(listSales.get(i).StaffId).get(0).StaffSurname,
                Brand.Searching(Product.Searching(listSales.get(i).ProductId).get(0).BrandId).get(0).BrandName  +" "+ Model.Searching(Product.Searching(listSales.get(i).ProductId).get(0).ModelId).get(0).ModelName ,
                listSales.get(i).ProcessDate,
                listSales.get(i).TotalPrice
            };
        }
            tblSales.setModel(new javax.swing.table.DefaultTableModel(
            data,
            new String [] {
                "Müşteri", "Satan Personel", "Ürün", "Satış Tarihi", "Fiyat"
            }
        ) {
            Class[] types = new Class [] {
                 java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        
    }//GEN-LAST:event_formWindowOpened

    private void tblSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSalesMouseClicked
        DefaultTableModel myModel = (DefaultTableModel) tblSales.getModel() ;
        int SelectedRowIndex = tblSales.getSelectedRow();
        
        txtCustomer.setText(myModel.getValueAt(SelectedRowIndex,0).toString());
        txtStaff.setText(myModel.getValueAt(SelectedRowIndex,1).toString());
        txtBrand.setText(myModel.getValueAt(SelectedRowIndex,2).toString());
        txtDate.setText(myModel.getValueAt(SelectedRowIndex,3).toString());
        txtPrice.setText(myModel.getValueAt(SelectedRowIndex,4).toString());

    }//GEN-LAST:event_tblSalesMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        this.setVisible(false);
        new SaleFrame().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaleUpdateListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaleUpdateListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaleUpdateListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaleUpdateListFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaleUpdateListFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSales;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtCustomer;
    private javax.swing.JTextField txtDate;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtStaff;
    // End of variables declaration//GEN-END:variables
}
